### ISSUE TITLE
Require a definition for the Duration tag

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-schemas#43] opened 2022-12-13 15:02 UTC
Based on the proposal to add several event process models to the HED specification, we made the suggestion of requiring the Duration tag to be grouped with a definition.

Since users can choose to use the Duration tag to represent the same information as what would be contained in the Onset and Offset tags, and these tags already need to be associated with a definition, it would help with education if this requirement was consistent.

On top of this, if we want to add intermediate event processes, than a definition would be necessary to associate the child event with its parent event.

**Comment by VisLab** [comment] 2023-03-28 16:33
Duplicate of #80. The discussion has been subsumed by this later issue.

**Closed as completed by VisLab** 2023-03-28 16:33 UTC
Labels: enhancement, specification
